package com.opencode.nfccardmanager.ui.test

object AppTestTags {
    const val LOGIN_USERNAME_INPUT = "login_username_input"
    const val LOGIN_PASSWORD_INPUT = "login_password_input"
    const val LOGIN_SUBMIT_BUTTON = "login_submit_button"
    const val LOGIN_ERROR_MESSAGE = "login_error_message"

    const val HOME_ROOT = "home_root"
    const val HOME_SESSION_CARD = "home_session_card"
    const val HOME_ROLE_SWITCH_ROW = "home_role_switch_row"
    const val HOME_SECTION_PRIMARY = "home_section_primary"
    const val HOME_SECTION_HIGH_RISK = "home_section_high_risk"
    const val HOME_SECTION_MANAGEMENT = "home_section_management"
    const val HOME_ENTRY_READ = "home_entry_read"
    const val HOME_ENTRY_WRITE = "home_entry_write"
    const val HOME_ENTRY_LOCK = "home_entry_lock"
    const val HOME_ENTRY_UNLOCK = "home_entry_unlock"
    const val HOME_ENTRY_TEMPLATE = "home_entry_template"
    const val HOME_ENTRY_AUDIT = "home_entry_audit"
    const val HOME_ENTRY_SETTINGS = "home_entry_settings"

    const val PERMISSION_DENIED_ROOT = "permission_denied_root"
    const val PERMISSION_DENIED_TITLE = "permission_denied_title"
    const val PERMISSION_DENIED_DESCRIPTION = "permission_denied_description"
    const val PERMISSION_DENIED_BACK_BUTTON = "permission_denied_back_button"

    const val LOCK_RISK_SUMMARY_CARD = "lock_risk_summary_card"
    const val LOCK_AUTHENTICITY_CARD = "lock_authenticity_card"
    const val LOCK_CONFIRM_BUTTON = "lock_confirm_button"
    const val LOCK_SIMULATE_SUCCESS_BUTTON = "lock_simulate_success_button"
    const val LOCK_RESULT_CARD = "lock_result_card"
    const val LOCK_RESULT_SOURCE = "lock_result_source"
    const val LOCK_DEMO_ONLY_BADGE = "lock_demo_only_badge"

    const val UNLOCK_BOUNDARY_CARD = "unlock_boundary_card"
    const val UNLOCK_AUTHENTICITY_CARD = "unlock_authenticity_card"
    const val UNLOCK_START_BUTTON = "unlock_start_button"
    const val UNLOCK_SIMULATE_SUCCESS_BUTTON = "unlock_simulate_success_button"
    const val UNLOCK_RESULT_CARD = "unlock_result_card"
    const val UNLOCK_RESULT_SOURCE = "unlock_result_source"
    const val UNLOCK_DEMO_ONLY_BADGE = "unlock_demo_only_badge"

    const val READ_RESULT_CARD = "read_result_card"
    const val READ_AUTHENTICITY_BADGE = "read_authenticity_badge"
    const val READ_RECOMMENDATION_CARD = "read_recommendation_card"
    const val READ_PRIMARY_CTA = "read_primary_cta"
    const val READ_SECONDARY_CTA = "read_secondary_cta"

    const val WRITE_ROOT = "write_root"
    const val WRITE_STAGE_CARD = "write_stage_card"
    const val WRITE_EXECUTION_SECTION = "write_execution_section"
    const val WRITE_VERIFICATION_SECTION = "write_verification_section"
    const val WRITE_NEXT_STEP_SECTION = "write_next_step_section"
    const val WRITE_START_BUTTON = "write_start_button"
    const val WRITE_RETRY_BUTTON = "write_retry_button"
    const val WRITE_SIMULATE_SUCCESS_BUTTON = "write_simulate_success_button"
    const val WRITE_DEMO_ONLY_BADGE = "write_demo_only_badge"

    const val FORMAT_STATUS_CARD = "format_status_card"
    const val FORMAT_RESULT_CARD = "format_result_card"
    const val FORMAT_WHAT_HAPPENED_SECTION = "format_what_happened_section"
    const val FORMAT_WHY_SECTION = "format_why_section"
    const val FORMAT_NEXT_STEP_SECTION = "format_next_step_section"
    const val FORMAT_START_BUTTON = "format_start_button"
    const val FORMAT_GO_WRITE_BUTTON = "format_go_write_button"

    const val AUDIT_LIST_ROOT = "audit_list_root"
    const val AUDIT_FILTER_KEYWORD = "audit_filter_keyword"
    const val AUDIT_RESET_FILTERS_BUTTON = "audit_reset_filters_button"
    const val AUDIT_EMPTY_STATE = "audit_empty_state"
    const val AUDIT_DETAIL_RESULT_CARD = "audit_detail_result_card"
    const val AUDIT_DETAIL_WHO_SECTION = "audit_detail_who_section"
    const val AUDIT_DETAIL_SEMANTICS_SECTION = "audit_detail_semantics_section"
    const val AUDIT_DETAIL_IMPACT_SECTION = "audit_detail_impact_section"
    const val AUDIT_DETAIL_MESSAGE_SECTION = "audit_detail_message_section"

    fun auditListItem(logId: Long): String = "audit_list_item_$logId"
}
